export { default as Bademeister } from "./Bademeister";
export { default as Bruder } from "./Bruder";
export { default as Eltern } from "./Eltern";
export { default as FreundIn } from "./FreundIn";
export { default as Krankenschwester } from "./Krankenschwester";
export { default as Lehrer } from "./Lehrer";
export { default as Oma } from "./Oma";
export { default as Opa } from "./Opa";
export { default as Schwester } from "./Schwester";
